name             'database'
maintainer       ''
maintainer_email ''
license          ''
description      'Installs/Configures database'
long_description 'Installs/Configures database'
version          '0.1.0'
depends 's3_file'
